### ISSUE TITLE
Does this action respect duration of iterations?

### ISSUE THREAD

**Issue by igorhrcek** [blombard/move-to-next-iteration#4]
👋 

I was wondering if this action respects the actual duration of iterations? For example, if I configure a cron to run it weekly on Monday, and we are in the middle of an iteration (that finishes next Monday), is it going to move issues to the next sprint today, or will it do that when it fires next time according to the iteration ending date?

**Comment by blombard** [comment]
I depends on the input parameters.
Specifically `iteration` and `new-iteration`. (https://github.com/blombard/move-to-next-iteration?tab=readme-ov-file#iteration)
```markdown
### iteration
Should be `last` or `current`.

### new-iteration
Should be `current` or `next`.
```

If you put `last` in `iteration` and `current` in `new-iteration` then every week it will only put items from the last iteration in the current iteration. (with you weekly cron)
=> This means, it will do nothing unless you are at the start of a new iteration and in this case, it will move all the items from the previous iteration to the current one.
