### ISSUE TITLE
Option to define excluded statuses instead

### ISSUE THREAD

**Issue by agarzola** [blombard/move-to-next-iteration#5]
We have several projects each with their own set of statuses, each of which may need to be adjusted from time to time. The _Done_ status, however, is the least likely to change, and it happens to be the only status we don’t need to move from one iteration to another.

I think it would be helpful to have the option to declare a set of excluded statuses that _should not_ cause issues to be moved, as opposed to a set of statuses that _should_ be moved (as is currently implemented). Would you accept a PR that implements this as an optional feature?

**Comment by blombard** [comment]
Hey @agarzola this definitely seems like a good idea so feel free to open a PR 👍

**Comment by agarzola** [comment]
I’ll submit a PR this week, then. Thanks, @blombard!
